function [C,Cu,Cx] = OCP_GEN_C_Cu_Cx(in1,in2,in3,parIdx)
%OCP_GEN_C_Cu_Cx
%    [C,Cu,Cx] = OCP_GEN_C_Cu_Cx(IN1,IN2,IN3,parIdx)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/09 12:24:35

C = zeros(0,1);
if nargout > 1
    Cu = zeros(0,8);
end
if nargout > 2
    Cx = zeros(0,14);
end
end
