function C = OCP_GEN_C(in1,in2,in3,parIdx)
%OCP_GEN_C
%    C = OCP_GEN_C(IN1,IN2,IN3,parIdx)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023/06/09 12:24:35

C = zeros(0,1);
end
